### ISSUE TITLE
Enabling MultiSampling and then resizing window crashes

### ISSUE THREAD

**Issue by gmriggs** [MarcStan/MonoGame.Framework.WpfInterop#12]
Hello, thank you for the great project

I was having some issues with getting multisampling to work with the version from nuget, so I tried compiling the latest version and set the PreferMultiSampling bool to true.

This seems to work initially, and everything appeared antialiased now. However, if I try to resize the window, I get the following crash:

D3D11Host.cs, line 534:
// enough time has passed to draw a single frame
// draw into cache
GraphicsDevice.SetRenderTarget(_cachedRenderTarget);
System.NullReferenceException: 'Object reference not set to an instance of an object.'

Both GraphicsDevice and _cachedRenderTarget do not appear to be null... if I try to catch the exception and push onwards, it gets other errors afterwards

I will work around these issues in the meantime, for now I am happy to see antialiasing in the WpfInterop app :)

**Comment by MarcStan** [comment]
Hi,

I changed some internals for version 1.7.0.

If you call "WpfGame.UseASingleSharedGraphicsDevice = true;" (before the WpfGame instance is created) the crash on resize will not occur anymore.

**Comment by gmriggs** [comment]
Hello,

I have set 'UseASingleSharedGraphicsDevice = true' at the beginning of the program, and double checked that this value is being set before the WpfGame is created.

With 'UseASingleSharedGraphicsDevice=true' and 'PreferMultiSampling=true', I still seem to get the same crash when resizing the window. As soon as I disable multisampling, the error goes away..

Is there a preferred way to enabled Multisampling in the application? Since WpfGraphicsDeviceService implements 2 interfaces, I am unable to set the PreferMultiSampling bool in that class to true from the WpfGraphicsDeviceService instance... so I have just been defaulting it to true directly inside of PreferMultiSampling for testing

**Comment by MarcStan** [comment]
Can you check whether the same happens with the WpfTest application from my repo? I used this to repro and it doesn't crash on resize.

Set UseASingleSharedGraphicsDevice to true in the App.xaml.cs and then press the "Show msaa" button.

If that also doesn't work for you then I need a bit more details about your system (OS Version, GPU).

**Comment by gmriggs** [comment]
Using WpfTest, by default resizing the MSAA window crashes, and then i set 'UseASingleSharedGraphicsDevice=true', and now the MSAA window can be successfully resized in the test app

Using the same settings in another app, I am getting the crash there, so I will dig into this further and see what the difference is between WpfTest and this other app...

Thanks for your help, I'll post back here when I find the difference

**Comment by gmriggs** [comment]
I can replicate the crash I am seeing in WpfTest by enabling MSAA in the main CubeDemoScene window:

CubeDemoScene.cs, line 34:

```
            new WpfGraphicsDeviceService(this)
            {
                PreferMultiSampling = true
            };
```

If 'UseASingleSharedGraphicsDevice=true', and 'PreferMultiSampling=true' in the main window, it seems to crash on resize there. If MSAA is enabled in the popup window, then it seems to work

**Comment by gmriggs** [comment]
In the meantime, I have temporarily bypassed this issue by disabling MSAA automatically in the app before resizing the viewport, and then re-enabling after resizing

**Comment by MarcStan** [comment]
I was able to reproduce it with the CubeDemoScene and fixed the issue (MonoGame still has some internal references until the next frame is drawn, so I simply dispose the previous rendertarget one frame later).

v1.7.1 should no longer crash!

**Comment by gmriggs** [comment]
Thank you, tested the latest version, everything works great!
