### ISSUE TITLE
Is there an equivalent to Microsoft.Xna.Framework.GameWindow?

### ISSUE THREAD

**Issue by FrancescoBonizzi** [MarcStan/MonoGame.Framework.WpfInterop#13]
Is there an equivalent to `Microsoft.Xna.Framework.GameWindow`, with methods such as `ClientSizeChanged`?

Thanks for you work!

**Comment by MarcStan** [comment]
Yes, WpfGame inherits from Image so you can make use of the existing WPF event "SizeChanged".

For the other stuff (such as AllowAltF4 and Title properties) you would have to write your own wrapper.

WpfGame is only a control and has no notion of its surrounding window (there could be more than one WpfGame inside the same window as [demoed here](https://github.com/MarcStan/MonoGame.Framework.WpfInterop/blob/master/WpfTest/Views/MultiSceneWindow.xaml)).

**Comment by FrancescoBonizzi** [comment]
Understood. Thanks, I abstracted the "game window" and implemented differently for `XNA` `GameWindow ` and `WPF` Window.
