### ISSUE TITLE
Blurry graphics

### ISSUE THREAD

**Issue by MickGyver** [MarcStan/MonoGame.Framework.WpfInterop#17]
First of all, thanks a lot for this control! 

I'm having one problem though, graphics are a bit blurry even if I use: spriteBatch.Begin(samplerState: SamplerState.PointClamp);

If I don't set to PointClamp, the graphics will be VERY blurry, but something else is causing the blur. What should I do to get "pixel perfect" graphics?

**Comment by MarcStan** [comment]
Are you using a monitor with DPI scaling of greater than 100%? If so [this might help](https://gitlab.com/MarcStan/MonoGame.Framework.WpfInterop/issues/17).

**Comment by MickGyver** [comment]
Thanks for the reply! DPI scaling of my monitor is at 100%, maybe the WPF app for some reason still is using a DPI other than 100%...

**Comment by MarcStan** [comment]
Can you check the resolution of the Game control as well (GraphicsDevice Width/Height)? It should match the pixel size on screen.

By default WPF determines the correct resolution for the game window.

**Comment by MickGyver** [comment]
The width and height of the game control match the width and height of the pixel size on the screen.
The attached image shows the problem to the left, and what it should look like to the right. the image has been scaled to 500%.
![wpf-monogame-blurred](https://user-images.githubusercontent.com/8739202/57567131-83efac80-73dd-11e9-8c50-09e5cfc43be0.png)

**Comment by MarcStan** [comment]
I took your image and loaded it into your SpriteToolBox. I scaled the image all the way to 1500% and the right figure remained pixel perfect (without any aliasing artifacts).

Once I switched to LinearClamp the right figure started to get blurry around the edges when scaled, so seems to me that PointClamp is working correctly.

Have you tested the behaviour in a basic MonoGame window as well?

If the behaviour there is the same, then it may not be an issue with WpfInterop itself.

**Comment by MickGyver** [comment]
Again, thank you for the input! PointClamp is working correctly. The behaaviour in a basic MonoGame window is correct, also in a MonoGame.Forms window. I'm converting an editor from WinForms to WPF: https://github.com/MickGyver/SpriteToolBox

**Comment by MarcStan** [comment]
I've created a sample that draws the same spriet in various scales (left to right) and with point, linear and anisotropic clamp (top to bottom).

At least to my eye it looks identical in regular monogame and the wpf intero.

This is what it look for me in regular monogame (MonoGame project in the solution):
![image](https://user-images.githubusercontent.com/8313404/57571673-88798c80-7400-11e9-8686-8b5cc0110693.png)

and in wpf interop (WpfTest -> "Sprite scene"):
![image](https://user-images.githubusercontent.com/8313404/57571670-83b4d880-7400-11e9-9792-643218bdeb06.png)

The samples are in the [feature/sprites](https://github.com/MarcStan/MonoGame.Framework.WpfInterop/tree/feature/sprites) branch I just pushed, perhaps you can check it out and tell me if it looks any different for you.

If I misunderstood your problem feel free to fork and edit to reproduce the problem. I'll take a look then.

**Comment by MickGyver** [comment]
Thanks! Your example is working perfectly for me also, but if I import the SpriteScene from that project into my project the blurring occurs. You can see from the zoomed in screenshot that the drawing of the whole window is slightly off (look around the edges).

![wpf-monogame-2](https://user-images.githubusercontent.com/8739202/57579343-5836fa00-74a3-11e9-9bc4-04ea4c90b6e3.png)
![wpf-monogame-3](https://user-images.githubusercontent.com/8739202/57579374-8ddbe300-74a3-11e9-85d9-4867124a37dc.png)

This is from the xaml, no extra sizing stuff etc:
```
<local:GameWindow Grid.Column="3" Grid.Row="3" x:Name="spriteWindow" />
```

**Comment by MickGyver** [comment]
The problem seems to be related to xaml layout. I created a simple project, with no margins etc. all is fine, but if I add a more complex grid and set up some margins, the blurriness appears. So is this perhaps a WPF bug?

**Comment by MarcStan** [comment]
I just had a look at your project and I spotted the problem:

![image](https://user-images.githubusercontent.com/8313404/57580129-2880f580-7495-11e9-8619-606a2281ace5.png)

WPF layouting uses double precision for all its layouting, as such the game window is "slightly" off by more than 0 pixels so WPF has to rescale the entire game to fit the area correctly. This then causes the blur.

The cause seems to be the use of `Auto` in your outermost grid (for toolbar and sidebar). I hardcoded them to specific values (e.g. 180/120) and the problem went away.

**Comment by MickGyver** [comment]
I just found out the same thing! When I added the property UseLayoutRounding="True" to the Window component, the blurring is gone, even if I leave all grid columns etc. to auto or *. 

Thank you so much for helping me troubleshoot the problem!
