### ISSUE TITLE
Crash in method PlatformSetup() of GraphicsDevice

### ISSUE THREAD

**Issue by mastertnt** [MarcStan/MonoGame.Framework.WpfInterop#2]
Tested on my laptop (DELL M4800). 
There is a crash during initialization.

Here's the exception details 

System.NullReferenceException was unhandled
  _HResult=-2147467261
  _message=La référence d'objet n'est pas définie à une instance d'un objet.
  HResult=-2147467261
  IsTransient=false
  Message=La référence d'objet n'est pas définie à une instance d'un objet.
  Source=MonoGame.Framework
  StackTrace:
       à Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformSetup()
       à Microsoft.Xna.Framework.Graphics.GraphicsDevice.Setup()
       à Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters)
       à MonoGame.Framework.WpfInterop.D3D11Host.InitializeGraphicsDevice()
       à MonoGame.Framework.WpfInterop.D3D11Host.OnLoaded(Object sender, RoutedEventArgs eventArgs)
       à System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       à System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       à System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       à System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
       à System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
       à System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
       à MS.Internal.LoadedOrUnloadedOperation.DoWork()
       à System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
       à System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
       à System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
       à System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
       à System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
       à System.Windows.Interop.HwndTarget.OnResize()
       à System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
       à System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       à MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       à MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       à System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       à MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
  InnerException:

**Comment by MarcStan** [comment]
What version of Monogame Framework where you using?

And can you provide a sample project so I can reproduce?

**Comment by mastertnt** [comment]
3.5.1.1679 with Visual Studio 2013 and your nuget package (1.1.1)
When i compile from your source with Visual Studio 2015, it works fine.

How can i send you a zipped sample ?

**Comment by MarcStan** [comment]
You can attach files to the comments in the issue here.

**Comment by mastertnt** [comment]
Ok i fixed my problem, sorry. I set the version of Monogame to DesktopGL... I changed it to WindowsDX and it works fine.

I suggest you to create a dependency of your nuget package on the correct version of the monogame package to avoid mistake :-)
