### ISSUE TITLE
Demo crashes when closing main window after opening a second window

### ISSUE THREAD

**Issue by Ziriax** [MarcStan/MonoGame.Framework.WpfInterop#3]
First of all, very nice work!

I found a little bug.

Launch your demo, and open a second window.

Then close the main window.

The app will crash.

Reason: the finalizer of the main window calls Dispose again. 

The way I fixed this, is by modifying D3D11Host, making it abstract, and further modifying

		private void Dispose(bool disposing)
		{
			if (_disposed)
				return;

			_disposed = true;

			GC.SuppressFinalize(this);

			OnDispose(disposing);
		}

		protected abstract void OnDispose(bool disposing);

Like this one cannot forget to implement OnDispose, one cannot call the Dispose base method, OnDispose will be only called once, and the finalizer will not call Dispose again if it was already called. 

Note because the finalizer runs in a different thread, disposing here might crash anyway...

Thanks,
Peter

**Comment by MarcStan** [comment]
Good catch.

Technically it was a fault in DemoScene (Dispose was called twice and the second call caused the crash on an already disposed resource).

I added a simple if (_disposed) check to prevent the crash.

v1.2.1 contains the changes.
