### ISSUE TITLE
Content.Load Exception

### ISSUE THREAD

**Issue by BradleyUffner** [MarcStan/MonoGame.Framework.WpfInterop#4]
protected override void LoadContent()
        {
            _defaultFont = Content.Load<SpriteFont>("DefaultFont");
        }

Fails with "No Graphics Device Service"

**Comment by MarcStan** [comment]
Did you create a 

        _graphicsDeviceManager = new WpfGraphicsDeviceService(this);

as it says in the readme?

This service is required and will internally hook up everything (same way as monogame does it). You must create it before using the GraphicsDevice and Content properties.

**Comment by Ziriax** [comment]
I had a similar problem. In my case I did create a WpfGraphicsDeviceService in the Initialize method, but I called the base Initialize method before creating it. Turns out that this base method calls LoadContent. So I called the base Initialize method afterwards instead (that feels wrong but it solved the problem)

**Comment by MarcStan** [comment]
That's the right thing to do in this case.

Internally the nuget package does this:

    protected override void Initialize()
    {
        base.Initialize();
        LoadContent();
    }

So when you call base.Initialize() it will automatically call LoadContent so you want the Service to be created before then.

This is the same behaviour as Monogame.

**Comment by BradleyUffner** [comment]
That fixed it, thank you!

You should be aware that the ReadMe has the base.Initialize call first also, you should probably update that.


    

> protected override void Initialize()
>     {
>         **base.Initialize();**
> 
>         // must be initialized. required by Content loading and rendering (will add itself to the Services)
>         _graphicsDeviceManager = new WpfGraphicsDeviceService(this);
> 
>         // wpf and keyboard need reference to the host control in order to receive input
>         // this means every WpfGame control will have it's own keyboard & mouse manager which will only react if the mouse is in the control
>         _keyboard = new WpfKeyboard(this);
>         _mouse = new WpfMouse(this);
>     }
