### ISSUE TITLE
How to use GameComponent Class with WpfInterop ?

### ISSUE THREAD

**Issue by polyminthe** [MarcStan/MonoGame.Framework.WpfInterop#5]
Hi thank you so much for your work, I really appreciate that lib.

I just have one question. 
I plan to use a Microsoft.Xna.Framework.GameComponent Class. But i have no idea what can i use in the 
:base()

Do you have implement some class for a "GameComponent" derived from WpfInterop Game ?
Thank you so much if you can show me some sample

**Comment by MarcStan** [comment]
There is no support for GameComponent as it directly depends on Game (which in turn always spawns its own window).

A new WpfGameComponent would have to be created. From what I see this wouldn't require too much work.
The main work would be to respect both the Update/Draw order as well as any changes to them during runtime.

If I find some free time, I may look into it.

**Comment by polyminthe** [comment]
Ok thank you, i got it. You answer so quickly ! Very nice ^^ Have a nice day.
 I am already so exiting to use WpfInterop

**Comment by MarcStan** [comment]
I added the two classes WpfGameComponent and WpfDrawableGameComponent in v1.3. It was even less work than I expected.

**Comment by polyminthe** [comment]
Waouhh so quickly 😀  Man thanks 👍👍  . Nice work.
