### ISSUE TITLE
There is an error running the new version

### ISSUE THREAD

**Issue by esengine** [MarcStan/MonoGame.Framework.WpfInterop#7]
System.TypeInitializationException: "The type initializer for "Microsoft.Xna.Framework.Graphics.GraphicsAdapter" throws an exception."
Failed to load type "SharpDX.Rectangle" from assembly "SharpDX, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1"

This prompt appeared after I updated to the new version. How can I solve it?

**Comment by MarcStan** [comment]
I don't know.

Can you give more details about the circumstances? Ideally provide a sample project for me to verify the behaviour.

I tested the nuget package with the WpfTest application in my repository and it worked just fine.

For one, Monogame 3.6 ships with SharpDX 2.6.3.0. Are you perhaps manually referencing another SharpDX version?

**Comment by esengine** [comment]
It automatically uses Sharpdx under my C drive. The version under my C drive is 2.6.3.

**Comment by MarcStan** [comment]
Both the Monogame Nuget package and the installed Monogame include SharpDX 2.6.3.

Are you using a different SharpDX version than monogame?

**Comment by esengine** [comment]
Yes, I used a different version. I used the source code of monogame and is on its development branch. It uses the sharpdx version of 4.0.1

**Comment by MarcStan** [comment]
Ah I see, then unfortunately you will also have to use my sourcecode with the fix you proposed.

I can't really merge it as it would cause potential breaking changes for people using the Monogame nuget package (and its SharpDX 2.6.3 version).

PS: If you aren't already using them, you might be interested in the feature/Unofficial-Msaa-Upgrade and feature/DpiScalingSupport branches of my project.

The first will give you MSAA inside the WPF hosted control, the later adds DPI scaling support on top of that (I had to make 2 tiny changes to the Monogame sourcecode, but you can port these to your Monogame source easily).
