### ISSUE TITLE
An error occurred when I quit the wpf program

### ISSUE THREAD

**Issue by esengine** [MarcStan/MonoGame.Framework.WpfInterop#9]
![image](https://user-images.githubusercontent.com/18465053/45534770-cbae3c00-b82e-11e8-8ead-e34b3e09fa4f.png)

I think there needs to be a judgment here, but this is a problem with monogame. Have you found this problem?

I think it should be modified like this:
```C#
if (_swapChain != null  && _swapChain.IsFullScreen)
                _swapChain.SetFullscreenState(false, null);
```

**Comment by MarcStan** [comment]
Yes, I mentioned it in #7. For the other branches in my repository I forked Monogame and had to make 2 changes. I've also [submitted them as a PR](https://github.com/MonoGame/MonoGame/pull/6412) but it was not yet merged.

Feel free to copy these changes over to your Monogame fork.

**Comment by esengine** [comment]
Ok, I will try to use your branch to help me solve these problems, thank you
